
services:
  server:
    build:
      context: ./server
    container_name: server
    ports:
      - "1234:1234"
    #entrypoint: sh /server/nc_server.sh
    #entrypoint: sh
  client:
    build:
      context: ./client
    container_name: client
    #entrypoint: sh /client/nc_client.sh
    #entrypoint: sh
    depends_on:
      - server
